name: 'Hunting Bears'
app_name: 'Hunting Bears Blog'
title: A blog about Free Software and Society
description: A blog about Free Software and Society.
author:
  name: 'Luis Alejandro Martínez Faneyth'
  first_name: 'Luis Alejandro'
  last_name: 'Martínez Faneyth'
  email: 'luis@huntingbears.com.ve'
  github: 'LuisAlejandro'
  twitter: 'LuisAlejandro'
  facebook: 'martinez.faneyth'
blog:
  twitter: 'BlgHuntingBears'
  facebook: 'BlogHuntingBears'
  googleplus: 'HuntingBearsVE'
  feed: 'BlogHuntingBears'
url: 'http://huntingbears.com.ve'
permalink: '/:title.html'
paginate: 10
paginate_path: 'page/:num'
exclude:
  - 'CNAME'
  - 'Readme.md'
  - 'requirements.txt'
  - 'scripts'
  - 'Makefile'
  - 'Dockerfile'
timezone: 'America/Caracas'
generator: 'Jekyll - Github Pages'
gems:
  - 'github-pages'
