name: 'Hunting Bears'
app_name: 'Hunting Bears Blog'
title: A blog about Free Software and Society
description: A blog about Free Software and Society.
author:
  name: 'Luis Alejandro Martínez Faneyth'
  first_name: 'Luis Alejandro'
  last_name: 'Martínez Faneyth'
  email: 'luis@huntingbears.com.ve'
  github: 'LuisAlejandro'
  twitter: 'LuisAlejandro'
  facebook: 'martinez.faneyth'
  paypal: 'martinezfaneyth'
blog:
  twitter: 'HuntingBearsWeb'
  facebook: 'HuntingBearsWeb'
  instagram: 'HuntingBearsWeb'
  googleplus: 'HuntingBearsVE'
  feed: 'HuntingBearsWeb'
# url: 'http://huntingbears.com.ve'
url: 'file:///home/huntingbears/Desarrollo/huntingbears.github.io/_site/'
permalink: 'pretty'
paginate: 20
paginate_path: 'page/:num'
exclude:
  - 'CNAME'
  - 'Readme.md'
  - 'requirements.txt'
  - 'scripts'
  - 'Makefile'
  - 'Dockerfile'
  - 'Gemfile'
timezone: 'America/Caracas'
generator: 'Jekyll - Github Pages'
plugins:
  - 'github-pages'
