name: 'Hunting Bears'
app_name: 'Blog Hunting Bears'
title_es: Un blog acerca de Software Libre y Sociedad
title_en: A blog about Free Software and Society
description_es: Un blog acerca de Software Libre y Sociedad.
description_en: A blog about Free Software and Society.
author:
  name: 'Luis Alejandro Martínez Faneyth'
  first_name: 'Luis Alejandro'
  last_name: 'Martínez Faneyth'
  email: 'luis@huntingbears.com.ve'
  github: 'LuisAlejandro'
  twitter: 'LuisAlejandro'
  facebook: 'martinez.faneyth'
blog:
  twitter: 'BlgHuntingBears'
  facebook: 'BlogHuntingBears'
  googleplus: 'HuntingBearsVE'
  feed: 'BlogHuntingBears'
url: 'http://huntingbears.com.ve'
permalink: '/:title.html'
paginate: 10
paginate_path: 'page/:num'
exclude:
  - 'TODO'
  - 'tools'
  - 'categorize.py'
  - 'compress.py'
  - 'newdraft.py'
  - 'publish.py'
  - 'Gemfile'
  - 'Makefile'
  - '.sublime'
safe: true
lsi: false
highlighter: 'pygments'
markdown: 'redcarpet'
redcarpet:
 extensions:
   - tables
timezone: 'America/Caracas'
generator: 'Jekyll - Github Pages'
